V0.1 first draft
turbot/steampipe-mod-aws-top-10 pull request #1
Opened 2023-07-05 18:05 UTC by judell

2023-07-10 20:03 UTC, cbruno10 requested changes
@judell Please see comments/questions, thanks!

2023-07-10 20:03 UTC, cbruno10 commented on top-10.sp
> +  description = "The top 10 AWS security items recommended on the AWS Security blog."
For this benchmark, if we're going to add more benchmarks based on AWS blog posts/docs, maybe an external doc would be helpful for this benchmark? The doc wouldn't need a lot of content, but would let us give a brief description and link (using Markdown) to the AWS blog post, e.g., https://github.com/turbot/steampipe-mod-aws-compliance/blob/main/gdpr/docs/gdpr_overview.md

2023-07-10 20:03 UTC, cbruno10 commented on top-10.sp
> +    benchmark.accurate_account_info,
```suggestion
    benchmark.aws_top_10_security_accurate_account_info,
```

We usually include the benchmark name in the control names as well so we can tell which benchmark each control belongs to

2023-07-10 20:03 UTC, cbruno10 commented on top-10.sp
> +  title = "1. Accurate account information"
Is there a description we can add here? If we can't find a good one or two line description to use, we can always use Markdown docs and copy and paste the content from the AWS blog for each item

2023-07-10 20:03 UTC, cbruno10 commented on top-10.sp
> +benchmark "aws_top_10" {
```suggestion
benchmark "aws_top_10_security" {
```

2023-07-10 20:03 UTC, cbruno10 commented on top-10.sp
> +    service = " AWS Security Top 10"
```suggestion
    service = "AWS"
```

I think I'd keep `service` tag as `AWS

2023-07-10 20:03 UTC, cbruno10 commented on top-10.sp
> +    category = " AWS Security Top 10"
```suggestion
    category = "Compliance"
```

Or:
```suggestion
    category = "Security"
```

We haven't `Security` as a category before, but could be a helpful category tag to describe this benchmark

2023-07-10 20:03 UTC, cbruno10 commented on top-10.sp
> +locals {
Should these tags move to `mod.sp`, like in https://github.com/turbot/steampipe-mod-aws-tags/blob/main/mod.sp#L2? If so, we could add the `plugin` tag to it, and then have another set of tags for this benchmark that are a result of merging those common tags in `mod.sp` and adding the `type = "Benchmark"` tag

2023-07-10 20:03 UTC, cbruno10 commented on mod.sp
> +      min_version = "0.101.0"
Is `min_version` actually supported yet? What version of Steampipe is required to use `min_version` in `mod.sp`?

2023-07-10 20:03 UTC, cbruno10 commented on mod.sp
> +      version = "*"
What min version of perimeter do we need?

2023-07-10 20:03 UTC, cbruno10 commented on mod.sp
> +      min_version = "0.101.0"
Also, do we actually need 0.101.0 as a min version? What dependencies exist in this version?

2023-07-10 20:03 UTC, cbruno10 commented on top-10.sp
> +    aws_compliance.control.vpc_security_group_restricted_common_ports,
Can you please sort the list of children (and in other benchmarks if required as well)?

2023-07-10 20:03 UTC, cbruno10 commented on top-10.sp
> +
```suggestion
```

2023-07-10 20:03 UTC, cbruno10 commented on top-10.sp
> +    benchmark.accurate_account_info,
```suggestion
    benchmark.aws_top_10_security_01_accurate_account_info,
```

Or

```suggestion
    benchmark.aws_top_10_security_1_accurate_account_info,
```

@judell Any thoughts on including the number of the item in the control name as well? Does it help (or hurt) readability at all?

2023-07-10 20:36 UTC, judell commented on top-10.sp
> +    service = " AWS Security Top 10"
Here's why.

![image](https://github.com/turbot/steampipe-mod-aws-security-top-10/assets/46509/d8e8c56a-f494-4326-9461-57f505c0d359)

Otherwise it gets lost among everything else. (That was Daemon's feedback on the well-architected mod too btw.)

I'm also using the leading-space hack to make it show up first.

Of course there are better ways to showcase a benchmark that expands on an existing mod, this is just a way that's possible now. 

I figure if you go to the trouble of cloning and running a specific mod, you care much more about what it provides than what its dependencies do.

2023-07-10 20:36 UTC, judell commented on top-10.sp
> +    category = " AWS Security Top 10"
See above comment about making the custom thing stand out from the crowd.

2023-07-10 20:39 UTC, judell commented on mod.sp
> +      min_version = "0.101.0"
I guess not? I used it because I was seeing a deprecation message when just using `version` but not I'm not seeing it.

2023-07-10 20:57 UTC, judell commented on mod.sp
> +      version = "*"
In general, how do we answer questions of the form "What version of x does y need?" in order to make these assertions?

2023-07-10 20:57 UTC, judell commented on mod.sp
> +      min_version = "0.101.0"
Per above, how do we find out?

2023-07-10 21:05 UTC, judell commented on top-10.sp
> +  description = "The top 10 AWS security items recommended on the AWS Security blog."
The context is at the top of the README, https://github.com/judell/steampipe-mod-aws-security-top-10/blob/v0.1/README.md, is that sufficient?

2023-07-11 20:36 UTC, cbruno10 commented on top-10.sp
> +  description = "The top 10 AWS security items recommended on the AWS Security blog."
This would be helpful when users are viewing the Hub page, e.g., https://hub.steampipe.io/mods/turbot/aws_compliance/controls/benchmark.cis_v120. Users can't see the README on the Hub and if they select this specific benchmark on this mod's Hub page, I think it'd be helpful to have more info on it.

2023-07-11 20:38 UTC, cbruno10 commented on top-10.sp
> +    service = " AWS Security Top 10"
Instead of creating a workaround that we'd want to revert later on, I think we should work on a broader, more permanent solution with @MichaelBurgess on how to have these mod controls show up better in the default view, as this also affects mods like the AWS Well-Architected mod. Else if people rely on these tags when running benchmarks in their commands or are used to seeing them, and we change them later on to align with other mods, I think it could cause some disruption.

2023-07-11 20:38 UTC, cbruno10 commented on top-10.sp
> +    category = " AWS Security Top 10"
This reply also covers the above point I believe - https://github.com/turbot/steampipe-mod-aws-security-top-10/pull/1#discussion_r1260255697

2023-07-11 20:39 UTC, cbruno10 commented on mod.sp
> +      min_version = "0.101.0"
If the mod loads ok with this code, then I think it is supported?

2023-07-11 20:39 UTC, cbruno10 commented on mod.sp
> +      version = "*"
If there are certain controls only available in a specific mod dependency version, we usually use that as a min version here.

2023-07-11 20:40 UTC, cbruno10 commented on mod.sp
> +      min_version = "0.101.0"
I don't think we need a plugin dependency if we have mod dependencies, as the mod dependencies would fail to install if the user doesn't have the min plugin version each mod dependency requires anyway

2023-07-12 19:05 UTC, judell commented on mod.sp
> +      version = "*"
How would you check that? Is there an automated way?

2023-07-12 19:06 UTC, judell commented on top-10.sp
> +  description = "The top 10 AWS security items recommended on the AWS Security blog."
>  Users can't see the README on the Hub 

Ah, OK.

Will do, then.

2023-07-12 19:06 UTC, judell commented on top-10.sp
> +    service = " AWS Security Top 10"
OK I'll file an issue for that.

2023-07-12 19:43 UTC, judell commented on top-10.sp
> +    service = " AWS Security Top 10"
Meanwhile, what do you think of this proposed change?

![image](https://github.com/turbot/steampipe-mod-aws-top-10/assets/46509/16ad25b0-c29b-4508-b711-0e5b1de0518e)

The screencast shows each of the four views before and after.

![output](https://github.com/turbot/steampipe-mod-aws-top-10/assets/46509/abb7fcb1-5752-4ca6-a66c-d225c7026a96)

2023-07-12 19:50 UTC, judell commented on mod.sp
> +      min_version = "0.101.0"
Good point, I'll remove the plugin dependency.

2023-07-13 15:42 UTC, cbruno10 commented on mod.sp
> +      version = "*"
No automated way today, you could use an older plugin version and then run all of the controls and see if any come with errors or relation not found errors. If we don't have a good sense of which version to use but know the latest version works, then we could use that version as a starting point for now.

2023-07-13 18:38 UTC, judell commented on top-10.sp
> +    service = " AWS Security Top 10"
@cody if we add `category` here:

```
  aws_top_10_tags = {
    category = "AWS Security Top 10"
    service = "AWS"
    type = "Benchmark"
  }
```  

then it prevents this mod from showing up under Other in the category view. The above proposed change would do the same for the well-architected mod.

2023-07-13 18:54 UTC, merged